name: Force README refresh

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "last refresh: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > .readme-refresh
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .readme-refresh
          git commit -m "chore: auto refresh README" || echo "no changes to commit"
          git push
